language: go
go_import_path: github.com/derailed/k9s
go:
  - "1.12"
  # - master

os:
  - linux
  - osx

dist: trusty
sudo: false

install: true

env:
  - GO111MODULE=on
  - GOPROXY=https://proxy.golang.org

script:
  - go build
  - go test ./...
