k9s:
  system:
    log_stream_cancelled: "ğŸ"
    new_version: "âš¡ï¸"
    default: "ğŸ“"
    locked: "ğŸ”’"
    unlocked: "âœï¸"

  prompt:
    query: "ğŸ¶"
    filter: "ğŸ©"

  status:
    info: "ğŸ˜"
    warn: "ğŸ˜—"
    error: "ğŸ˜¡"

  xray:
    namespaces: "ğŸ—‚"
    default_gvr: "ğŸ“"
    nodes: "ğŸ–¥"
    pods: "ğŸš›"
    services: "ğŸ’â€â™€ï¸"
    service_accounts: "ğŸ’³"
    persistent_volumes: "ğŸ“š"
    persistent_volume_claims: "ğŸŸ"
    secrets: "ğŸ”’"
    horizontal_pod_autoscalers: "â™ï¸"
    config_maps: "ğŸ—º"
    deployments: "ğŸª‚"
    stateful_sets: "ğŸ"
    daemon_sets: "ğŸ˜ˆ"
    replica_sets: "ğŸ‘¯â€â™‚ï¸"
    cluster_roles: "ğŸ‘©â€"
    roles: "ğŸ‘¨ğŸ»â€"
    network_policies: "ğŸ“•"
    pod_disruption_budgets: "ğŸ·"
    pod_security_policies: "ğŸ‘®â€â™‚ï¸"
    containers: "ğŸ³"
    report: "ğŸ§¼"
    issue_0: "ğŸ‘"
    issue_1: "ğŸ”Š"
    issue_2: "â˜£ï¸"
    issue_3: "ğŸ§¨"
